# Generated by Django 4.0 on 2021-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='gender',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_categoryies', to='gender.Gender'),
        ),
    ]
