# Generated by Django 4.0 on 2021-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0002_remove_gender_sub_category_gender_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='sub_category',
        ),
    ]
