# Generated by Django 4.0 on 2021-12-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0006_gender_sub_category_alter_gender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='sub_category',
        ),
    ]
