# Generated by Django 4.0 on 2021-12-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0008_gender_genders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='genders',
        ),
    ]
