# Generated by Django 4.0 on 2021-12-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman')], max_length=255),
        ),
    ]
