# Generated by Django 4.0 on 2021-12-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0008_user_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
