# Generated by Django 4.0 on 2021-12-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0010_alter_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
    ]
