# Generated by Django 4.0 on 2021-12-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0011_remove_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='last name'),
        ),
    ]
