# Generated by Django 4.0 on 2021-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_personal_gender_personal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='number',
            field=models.IntegerField(),
        ),
    ]
