# Generated by Django 4.0 on 2021-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_personal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
