# Generated by Django 4.0 on 2021-12-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
        ('personal', '0007_alter_personal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='gender',
        ),
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.ManyToManyField(related_name='genders', to='gender.Gender'),
        ),
    ]
