# Generated by Django 4.0 on 2021-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0005_remove_gender_sub_category'),
        ('personal', '0011_remove_personal_gender_personal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='gender',
        ),
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.ManyToManyField(related_name='categories', to='gender.Gender'),
        ),
    ]
