# Generated by Django 4.0 on 2021-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0007_remove_gender_sub_category'),
        ('personal', '0012_remove_personal_gender_personal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='gender',
            field=models.ManyToManyField(related_name='gen', to='gender.Gender'),
        ),
    ]
