# Generated by Django 4.0 on 2021-12-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_alter_personal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='author',
        ),
    ]
