# Generated by Django 4.0 on 2021-12-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_user_user_type'),
        ('personal', '0016_remove_personal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentications.user', verbose_name='Личный кабинет'),
        ),
    ]
