# Generated by Django 4.0 on 2021-12-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0009_remove_gender_genders'),
        ('personal', '0019_remove_personal_person_personal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen', to='gender.gender'),
        ),
    ]
