# Generated by Django 4.0 on 2021-12-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0009_remove_gender_genders'),
        ('personal', '0020_personal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gen', to='gender.gender'),
            preserve_default=False,
        ),
    ]
