# Generated by Django 4.0 on 2021-12-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_alter_personal_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
