# Generated by Django 4.0 on 2021-12-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_user_user_type'),
        ('products', '0004_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.user', verbose_name='Автор поста'),
        ),
    ]
